---
settings:
  name: VSC, VASA Provider, and SRA 9.7
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti VSC, VASA Provider e SRA
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - title: Avvio rapido
    url: "/qsg.html"
  - section: deploy
  - section: manage
  - title: Note legali
    url: "/legal-notices.html"
