---
permalink: deploy/concept-migration-of-disaster-recovery-setup-from-windows-to-appliance.html 
sidebar: sidebar 
keywords: migration, windows, SRM, appliance, 
summary: 'Se si utilizza Site Recovery Manager (SRM) basato su Windows per il disaster recovery e si desidera utilizzare SRM Appliance per la stessa configurazione, eseguire la migrazione della configurazione di disaster recovery di Windows all"SRM basato sull"appliance.' 
---
= Migrazione di Windows SRM all'appliance SRM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza Site Recovery Manager (SRM) basato su Windows per il disaster recovery e si desidera utilizzare SRM Appliance per la stessa configurazione, eseguire la migrazione della configurazione di disaster recovery di Windows all'SRM basato sull'appliance.

Le fasi della migrazione del disaster recovery sono:

. Aggiornamento dell'appliance virtuale esistente per VSC, VASA Provider e SRA alla versione 9.7.1.
+
link:task-upgrade-to-the-9-7-1-virtual-appliance-for-vsc-vasa-provider-and-sra.html["Effettua l'upgrade all'appliance virtuale 9.7.1 per VSC, VASA Provider e SRA"^]

. Migrazione di Storage Replication Adapter basato su Windows a un SRA basato su appliance.
. Migrazione dei dati di Windows SRM all'appliance SRM.


https://docs.vmware.com/en/Site-Recovery-Manager/8.2/com.vmware.srm.install_config.doc/GUID-F39A84D3-2E3D-4018-97DD-5D7F7E041B43.html["Fare clic qui"^] per i passaggi dettagliati.
