---
permalink: deploy/concept-guidelines-for-using-vsc-standard-roles.html 
sidebar: sidebar 
keywords: guidelines, using, VSC standard roles 
summary: Quando si lavora con i ruoli standard di Virtual Storage Console per VMware vSphere, è necessario seguire alcune linee guida. 
---
= Linee guida per l'utilizzo dei ruoli standard VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si lavora con i ruoli standard di Virtual Storage Console per VMware vSphere, è necessario seguire alcune linee guida.

Non modificare direttamente i ruoli standard. In tal caso, VSC sovrascriverà le modifiche ogni volta che si aggiorna VSC. Il programma di installazione aggiorna le definizioni dei ruoli standard ogni volta che si aggiorna VSC. In questo modo si garantisce che i ruoli siano aggiornati per la versione di VSC e per tutte le versioni supportate di vCenter Server.

Tuttavia, è possibile utilizzare i ruoli standard per creare ruoli personalizzati in base all'ambiente. A tale scopo, è necessario copiare il ruolo standard VSC e quindi modificare il ruolo copiato. Creando un nuovo ruolo, è possibile mantenere questo ruolo anche quando si riavvia o si aggiorna il servizio VSC Windows.

Di seguito sono riportati alcuni dei modi in cui è possibile utilizzare i ruoli standard di VSC:

* Utilizzare i ruoli VSC standard per tutte le attività VSC.
+
In questo scenario, i ruoli standard forniscono tutti i privilegi di cui un utente ha bisogno per eseguire le attività VSC.

* Combina i ruoli per espandere le attività che un utente può eseguire.
+
Se i ruoli VSC standard forniscono una granularità eccessiva per l'ambiente, è possibile espandere i ruoli creando gruppi di livello superiore che contengono più ruoli.

+
Se un utente deve eseguire altre attività non VSC che richiedono ulteriori privilegi nativi di vCenter Server, è possibile creare un ruolo che fornisca tali privilegi e aggiungerlo anche al gruppo.

* Crea ruoli più specifici.
+
Se l'azienda richiede l'implementazione di ruoli più restrittivi rispetto ai ruoli VSC standard, è possibile utilizzare i ruoli VSC per creare nuovi ruoli.

+
In questo caso, clonare i ruoli VSC necessari e modificare il ruolo clonato in modo che disponga solo dei privilegi richiesti dall'utente.


