---
permalink: deploy/reference-sra-fails-to-perform-optimally-in-a-highly-scaled-environment.html 
sidebar: sidebar 
keywords: sra, fails, to, perform, optimally, highly, scaled, environment, 
summary: SRA non funziona in modo ottimale in un ambiente altamente scalabile 
---
= SRA non funziona in modo ottimale in un ambiente altamente scalabile
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Problema

SRA non riesce a funzionare in modo ottimale in un ambiente altamente scalabile (se VMware ha specificato limiti massimi come 250 PG, 250 RPS, 5000 VM) e potrebbero verificarsi problemi come un errore di timeout o un timeout ONTAP.



== Azione correttiva

È necessario modificare gli intervalli di timeout.

link:reference-configure-storage-replication-adapter-for-highly-scaled-environment.html["Configurazione di Storage Replication Adapter per ambienti altamente scalabili"]

[NOTE]
====
È inoltre possibile modificare le impostazioni di memoria per la scalabilità e le prestazioni dell'appliance virtuale per VSC, VASA Provider e SRA in configurazioni altamente scalate.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/tune_memory_settings_of_VM_VSC%2C_VASA_Provider%2C_and_SRA_for_scale_and_performance[]

====