---
permalink: deploy/task-enable-datastore-mounting-across-different-subnets.html 
sidebar: sidebar 
keywords: enabling, datastore, mounting, across, different, subnets, 
summary: 'Se si utilizza iSCSI o NFS e la subnet è diversa tra gli host ESXi e il sistema di storage, è necessario modificare i file delle preferenze di Virtual Storage Console per VMware vSphere. Se non si modifica il file delle preferenze, il provisioning del datastore non riesce perché (VSC) non può montare il datastore.' 
---
= Attiva il montaggio del datastore su diverse subnet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza iSCSI o NFS e la subnet è diversa tra gli host ESXi e il sistema di storage, è necessario modificare i file delle preferenze di Virtual Storage Console per VMware vSphere. Se non si modifica il file delle preferenze, il provisioning del datastore non riesce perché (VSC) non può montare il datastore.

.A proposito di questa attività
Quando il provisioning del datastore non riesce, VSC registra i seguenti messaggi di errore:

`Unable to continue. No ip addresses found when cross-referencing kernel ip addresses and addresses on the controller.`

`Unable to find a matching network to NFS mount volume to these hosts.` ``

.Fasi
. Accedere all'istanza di vCenter Server.
. Avviare la console di manutenzione utilizzando la macchina virtuale dell'appliance unificata.
+
link:task-access-virtual-appliance-maiintenance-console-options.html["Accedere alle opzioni della console di manutenzione dell'appliance virtuale per VSC, VASA Provider e SRA"]

. Invio `4` Per accedere all'opzione *supporto e diagnostica*.
. Invio `2` Per accedere all'opzione *Access Diagnostic Shell*.
. Invio `vi /opt/netapp/vscserver/etc/kamino/kaminoprefs.xml` per aggiornare `kaminoprefs.xml` file.
. Aggiornare `kaminoprefs.xml` file.
+
[cols="1a,1a"]
|===
| Se si utilizza... | Eseguire questa operazione... 


 a| 
ISCSI
 a| 
Modificare il valore della chiave di immissione `default.allow.iscsi.mount.networks` Da TUTTO al valore delle reti host ESXi.



 a| 
NFS
 a| 
Modificare il valore della chiave di immissione `default.allow.nfs.mount.networks` Da TUTTO al valore delle reti host ESXi.

|===
+
Il file delle preferenze include valori di esempio per queste chiavi di immissione.

+
[NOTE]
====
Il valore "`ALL`" non indica tutte le reti. Il valore "`ALL`" consente di utilizzare tutte le reti corrispondenti, tra l'host e il sistema di storage, per il montaggio degli archivi dati. Quando si specificano le reti host, è possibile attivare il montaggio solo attraverso le subnet specificate.

====
. Salvare e chiudere `kaminoprefs.xml` file.

