---
permalink: manage/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, for, storage, systems, 
summary: È possibile utilizzare Virtual Storage Console per VMware vSphere per impostare le credenziali predefinite per un sistema storage nel vCenter Server. 
---
= Impostare le credenziali predefinite per i sistemi storage
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Virtual Storage Console per VMware vSphere per impostare le credenziali predefinite per un sistema storage nel vCenter Server.

.Prima di iniziare
È necessario selezionare il vCenter Server che si desidera utilizzare per creare le credenziali predefinite.

.A proposito di questa attività
Se si impostano le credenziali predefinite per i sistemi di storage, Virtual Storage Console (VSC) utilizza queste credenziali per accedere a un sistema di storage che VSC ha appena scoperto. Se le credenziali predefinite non funzionano, è necessario accedere manualmente al sistema di storage. VSC e SRA supportano l'aggiunta di credenziali di sistema storage a livello di cluster o di SVM. Tuttavia, il provider VASA funziona solo con le credenziali a livello di cluster.

.Fasi
. Nella pagina VSC *Home*, fare clic su menu:Impostazioni[Impostazioni amministrative > Configura credenziali predefinite per il sistema di storage].
. Nella finestra di dialogo *Storage System Default Credentials* (credenziali predefinite del sistema di storage), immettere il nome utente e la password del sistema di storage.
+
Le credenziali dello storage controller vengono assegnate in ONTAP in base alla coppia di nome utente e password. Le credenziali dello storage controller possono essere l'account amministratore o un account personalizzato che utilizza RBAC (role-based access control).

+
Non è possibile utilizzare VSC per modificare i ruoli associati alla coppia di nome utente e password del controller di storage. Per modificare o creare un nuovo ruolo utente ONTAP da utilizzare con l'appliance virtuale per VSC, provider VASA e SRA, è possibile utilizzare Gestione sistema.

+
Consultare la sezione "`Configurazione dei ruoli e dei privilegi utente`" nella _Guida all'installazione e all'installazione di Virtual Storage Console, VASA Provider e Storage Replication Adapter per VMware® vSphere per la versione 9.7_.

. Fare clic su *OK* per salvare le credenziali predefinite.


.Al termine
Se le credenziali del sistema di storage sono state aggiornate perché un sistema di storage ha riportato lo stato "`Authentication Failure`" (errore di autenticazione), fare clic sull'opzione *REDISCOVER ALL* (RISCOPRI TUTTI) disponibile nella pagina *Storage Systems* (sistemi di storage). In questo modo, VSC tenta di connettersi al sistema di storage utilizzando le nuove credenziali.
