---
permalink: manage/task-pair-protected-and-recovery-sites.html 
sidebar: sidebar 
keywords: pairing, protected, recovery, sites, 
summary: 'Per consentire a Storage Replication Adapter (SRA) di rilevare i sistemi storage, è necessario associare i siti protetti e di ripristino creati utilizzando vSphere Client.' 
---
= Associare siti protetti e di ripristino
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per consentire a Storage Replication Adapter (SRA) di rilevare i sistemi storage, è necessario associare i siti protetti e di ripristino creati utilizzando vSphere Client.

.Prima di iniziare
* È necessario aver installato Site Recovery Manager (SRM) nei siti protetti e di ripristino.
* È necessario aver installato SRA nei siti protetti e di ripristino.


.A proposito di questa attività
Le configurazioni fan-out di SnapMirror sono quelle in cui un volume di origine viene replicato in due diverse destinazioni. Questi creano un problema durante il ripristino quando SRM deve ripristinare la macchina virtuale dalla destinazione.

[NOTE]
====
Storage Replication Adapter (SRA) non supporta le configurazioni di SnapMirror fan-out.

====
.Fasi
. Fare doppio clic su *Site Recovery* nella home page di vSphere Client, quindi fare clic su *Sites*.
. Fare clic sul menu:oggetti[azioni > Associa siti].
. Nella finestra di dialogo *Pair Site Recovery Manager Servers*, immettere l'indirizzo del Platform Services Controller del sito protetto, quindi fare clic su *Next*.
. Nella sezione *Select vCenter Server*, procedere come segue:
+
.. Verificare che vCenter Server del sito protetto venga visualizzato come candidato corrispondente per l'associazione.
.. Immettere le credenziali amministrative SSO, quindi fare clic su *fine*.


. Se richiesto, fare clic su *Sì* per accettare i certificati di protezione.


.Risultati
I siti protetti e di ripristino vengono visualizzati nella finestra di dialogo oggetti.
